---
pipeline_constants:
  GITHUB_ORGANIZATION_NAME:
  GITHUB_BOT_NAME:
  GITHUB_BOT_USER_NAME:
  GITHUB_BOT_EMAIL:
  GITHUB_AUTHORIZED_USERS:

  BUILDS_WORKSPACE_DIR: /var/lib/host-os
  BUILDS_CONFIG_FILE: config/host_os.yaml
  MOCK_CONFIG_FILE: config/mock/CentOS/7/CentOS-7-ppc64le.cfg

  MAIN_CENTOS_REPO_RELEASE_URL: http://mirror.centos.org/altarch/7
  MAIN_EPEL_REPO_RELEASE_URL: http://download.fedoraproject.org/pub/epel/7
  CENTOS_ALTERNATE_MIRROR_RELEASE_URL:
  EPEL_ALTERNATE_MIRROR_RELEASE_URL:

  UPLOAD_SERVER_HOST_NAME:
  UPLOAD_SERVER_USER_NAME:
  UPLOAD_SERVER_BUILDS_DIR_PATH:
  UPLOAD_SERVER_WEEKLY_DIR_PATH:
  UPLOAD_SERVER_DEVEL_DIR_PATH:

  NIGHTLY_BUILDS_CRON_EXPRESSION: '0 22 * * *'
  WEEKLY_BUILDS_CRON_EXPRESSION: '0 11 * * 3'

  SLACK_NOTIFICATION_RECIPIENT:
  SLACK_TEAM_DOMAIN:
  # Generate at https://my.slack.com/services/new/jenkins-ci
  SLACK_TOKEN:

  BUILD_INFORMATION_DIR: 'info'
