---
java_home: "/usr/lib64/jvm/jre"
java_initial_heap_size: "512M"
java_max_heap_size: "1024M"
java_debug: "5"

jenkins_url: "https://{{ansible_hostname}}/"
jenkins_log_file: "/var/log/jenkins/jenkins.log"
jenkins_plugins:
  # Checkout git repositories
  - git
  # Support for GitHub repositories
  - github
  # Execute Jenkins groovy scripts
  - groovy
  # Create jobs dynamically
  - job-dsl
  # Hide password parameters
  - mask-passwords
  # Show when scheduled builds will execute
  - next-executions
  # Allow job parameters
  - parameterized-trigger
  # Easily rebuild a job
  - rebuild
  # Add SSH key credentials
  - ssh-credentials
  # Connect to slaves using SSH
  - ssh-slaves
  # Mark logs with timestamps
  - timestamper
  # Create pipeline jobs
  - workflow-aggregator
  # Create more flexible pipeline jobs
  - workflow-multibranch
  # Make HTTP requests from Jenkins pipelines
  - http_request
  # Small, miscellaneous utility steps for Pipeline Plugin jobs
  - pipeline-utility-steps
  # Allows a pipeline job to notify a status for any GitHub commit
  - pipeline-githubnotify-step
  # Lock resources which are shared among builds
  - lockable-resources
  # Extended visualization of Pipeline build history
  - pipeline-stage-view
  # New Jenkins user experience
  - blueocean
  # Slack notifications
  - slack
